const modules = require('./modules')
const app = modules.express()

app.use(modules.cookie_parser())
app.use(modules.morgan('dev'))
app.use(modules.body_parser.urlencoded({ extended: false }))
app.use(modules.body_parser.json())
app.use(modules.cors())
app.use(modules.compression())
app.use(modules.helmet())
app.use(modules.session({ name: 'session_ID', secret: 'Pr@veenR@j@@@)$(&)', resave: false, saveUninitialized: true, cookie: { maxAge: 60000 } }))


app.use(modules.upload())

app.post('/login', modules.routes.Login)
app.post('/api-changepassword', modules.routes.changePassword)
app.get('/logout', modules.routes.logout)
app.get('/api-loadgst',modules.routes.getgst)
app.post('/api-gstinsert',modules.routes.gstinsert)

app.get('/api-loadcustomer',modules.routes.getcustomer)
app.post('/api-custinsert',modules.routes.customerinsert)
app.post('/api-prodinsert',modules.routes.productinsert)
app.get('/api-loadproduct',modules.routes.getproduct)
app.get('/api-loadcustomerlist',modules.routes.loadcustomerlist)
app.get('/api-loadproductlist',modules.routes.getproductlist)
app.post('/api-insertprodlist',modules.routes.productionlist)
app.get('/api-getproductlist/:custname/:date/:id',modules.routes.getproduct_list)
app.post('/api-moveprod',modules.routes.move_prod)
app.get('/api-getproductionlist',modules.routes.getproduction_list)
app.get('/api-getserialnumber',modules.routes.get_serialnnumber)
app.get('/api-formulainfo/:id',modules.routes.formula_id)
app.post('/api-updateformula',modules.routes.update_formula)
app.get('/api-getprdlist/:id',modules.routes.get_prdlist)
app.post('/api-cancelprod',modules.routes.cancel_prod)
app.get('/api-getquotationserialnumber',modules.routes.get_quotationserialnumber)

app.post('/api-insertqtr',modules.routes.insert_qtr)
app.get('/api-getqtrlist/:id',modules.routes.getqtr_list)
app.post('/api-create_quatation',modules.routes.createquatation)
app.post('/api-cancelrequestqto',modules.routes.cancel_requestqto)
app.get('/api-getquatationlist',modules.routes.getquatation_list)
app.post('/api-qotamount',modules.routes.qot_amount)
app.get('/api-getqutono/:id',modules.routes.getquto_no)
app.post('/api-cancelqto',modules.routes.cancel_qto)
app.get('/api-getqtrlistprint/:id',modules.routes.getqtrlist_print)

app.listen(7777, () => console.log(`App listening on port 7777`))
